
def test_login_ok():
    raise Exception()
